### ISSUE TITLE
New contact details

### ISSUE THREAD

**Issue by murugancmi** [MuruganR96/DeepSpeech1#1]
Hi @MuruganR96  i know it's not a  place to ask contact info, but i can't able to find other way to reach you can i know your contact details you can drop me on murugan@telecmi.com

**Comment by MuruganR96** [comment]
Sir tell me sir. How can I help you?

**Comment by murugancmi** [comment]
i need your help to implement deep speech

**Comment by MuruganR96** [comment]
muruganrajenthirean@gmail.com sir pls contact my personal email...

**Comment by MuruganR96** [comment]
which way to implement our deepspeech @murugancmi  sir.

**Comment by murugancmi** [comment]
please have a look your gmail account and please share your contact 




Get Outlook for Android







On Mon, Nov 19, 2018 at 10:10 PM +0530, "MuruganR96" <notifications@github.com> wrote:












which way to implement our deepspeech @murugancmi  sir.

**Comment by MuruganR96** [comment]
8675771077 and muruganrajenthirean@gmail.com

**Comment by murugancmi** [comment]
number is not reachable 




Get Outlook for Android







On Mon, Nov 19, 2018 at 10:14 PM +0530, "MuruganR96" <notifications@github.com> wrote:










8675771077 and muruganrajenthirean@gmail.com



On Mon 19 Nov, 2018, 10:11 PM Murugan Pandian <notifications@github.com

wrote:



> please have a look your gmail account and please share your contact

>

>

>

>

> Get Outlook for Android

>

>

>

>

>

>

>

> On Mon, Nov 19, 2018 at 10:10 PM +0530, "MuruganR96" <

**Comment by murugancmi** [comment]
you can teach me at 9894396168




On Mon, Nov 19, 2018 at 10:14 PM +0530, "MuruganR96" <notifications@github.com> wrote:










8675771077 and muruganrajenthirean@gmail.com



On Mon 19 Nov, 2018, 10:11 PM Murugan Pandian <notifications@github.com

wrote:



> please have a look your gmail account and please share your contact

>

>

>

>

> Get Outlook for Android

>

>

>

>

>

>

>

> On Mon, Nov 19, 2018 at 10:10 PM +0530, "MuruganR96" <

**Comment by MuruganR96** [comment]
7286880229
